import { formatValue } from "@/features/admin/adminDisplay";
import type { AdminDatabase } from "@/features/admin/adminModels";
import type { AdminSqlState } from "@/features/admin/hooks/useAdminConsoleState";

interface AdminSqlSectionProps {
  sql: AdminSqlState;
}

export function AdminSqlSection({ sql }: AdminSqlSectionProps) {
  return (
    <div className="admin-section-grid">
      <article className="admin-panel admin-panel--wide">
        <div className="admin-panel__header">
          <div>
            <div className="mini-card__label">Advanced Postgres access</div>
            <h3>SQL editor</h3>
          </div>
          <div className="admin-inline-pills">
            <span className="pill">{sql.selectedDatabaseMeta.label}</span>
            <span className="pill">single statement only</span>
            <span className="pill">max 250 rows returned</span>
          </div>
        </div>
        <label>
          Database
          <select
            value={sql.selectedDatabase}
            onChange={(event) =>
              sql.setSelectedDatabase(event.target.value as AdminDatabase)
            }
          >
            {sql.databaseOptions.map((database) => (
              <option
                key={database.id}
                value={database.id}
                disabled={database.disabled}
              >
                {database.label}
              </option>
            ))}
          </select>
        </label>
        <div className="button-row">
          <button
            className="button button--ghost"
            type="button"
            onClick={() =>
              sql.setSqlDraft(
                `SELECT table_name FROM information_schema.tables WHERE table_schema = '${sql.selectedRelationSchemaName || sql.defaultSchemaName}' ORDER BY table_name`,
              )
            }
          >
            List tables
          </button>
          <button
            className="button button--ghost"
            type="button"
            onClick={() =>
              sql.setSqlDraft(
                sql.selectedRelationName
                  ? `SELECT column_name, data_type, is_nullable FROM information_schema.columns WHERE table_schema = '${sql.selectedRelationSchemaName || sql.defaultSchemaName}' AND table_name = '${sql.selectedRelationName}' ORDER BY ordinal_position`
                  : `SELECT column_name, data_type, is_nullable FROM information_schema.columns WHERE table_schema = '${sql.selectedRelationSchemaName || sql.defaultSchemaName}' ORDER BY table_name, ordinal_position`,
              )
            }
          >
            Inspect columns
          </button>
          <button
            className="button button--ghost"
            type="button"
            onClick={() =>
              sql.setSqlDraft(
                `CREATE TABLE IF NOT EXISTS ${sql.selectedRelationSchemaName || sql.defaultSchemaName}.sample_admin_table (\n  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n  tenant_id text NOT NULL DEFAULT 'shared',\n  created_at timestamptz NOT NULL DEFAULT now()\n)`,
              )
            }
          >
            Create table template
          </button>
        </div>
        <textarea
          rows={18}
          value={sql.sqlDraft}
          onChange={(event) => sql.setSqlDraft(event.target.value)}
        />
        <div className="button-row">
          <button
            className="button button--primary"
            type="button"
            onClick={() => void sql.runSql()}
            disabled={sql.sqlBusy || !sql.canRunSql}
          >
            {sql.sqlBusy ? "Running..." : "Run SQL"}
          </button>
          <button
            className="button button--ghost"
            type="button"
            onClick={sql.resetSqlDraft}
          >
            Reset editor
          </button>
        </div>
      </article>

      <article className="admin-panel">
        <div className="admin-panel__header">
          <div>
            <div className="mini-card__label">Result</div>
            <h3>
              {sql.sqlResult
                ? sql.sqlResult.statement_type.toUpperCase()
                : "Waiting for execution"}
            </h3>
          </div>
          {sql.sqlResult ? (
            <span className="pill">{sql.sqlResult.row_count} rows</span>
          ) : null}
        </div>
        {sql.sqlResult ? (
          <>
            <div className="admin-inline-pills">
              {sql.sqlResult.truncated ? <span className="pill">truncated</span> : null}
              <span className="pill">
                {sql.sqlResult.columns.length ? "query result" : "mutation result"}
              </span>
            </div>
            {sql.sqlResult.columns.length ? (
              <div className="table-wrap admin-table-wrap">
                <table className="surface-table surface-table--dense">
                  <thead>
                    <tr>
                      {sql.sqlResult.columns.map((column) => (
                        <th key={column}>{column}</th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {sql.sqlResult.rows.map((row, index) => (
                      <tr key={index}>
                        {sql.sqlResult?.columns.map((column) => (
                          <td key={`${index}:${column}`}>
                            {formatValue(row[column])}
                          </td>
                        ))}
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            ) : (
              <div className="empty-state">
                Statement executed successfully. {sql.sqlResult.row_count} rows were
                affected.
              </div>
            )}
          </>
        ) : (
          <div className="empty-state">
            Run a query here for schema changes, migrations, or deeper inspection.
          </div>
        )}
      </article>
    </div>
  );
}
